export const assets = {
  heroBg: "/assets/hero-bg.png",
  heroSky: "/assets/background sky.webp",
  heroDashboard: "/assets/dashboard.webp",
  heroVineyard: "/assets/vineyard.webp",
  logoStrip: "/assets/logo-strip.png",
  vinoHubWordmark: "/assets/VinoHub.svg",
  vinoHubLarge: "/assets/VinoHub.svg",
  aiIcon: "/assets/ai-icon.png",
  excelIcon: "/assets/excel-logo.png",
  hubScreenshot: "/assets/hub-screenshot.png",
  salesSheetScreenshot: "/assets/sales-sheet-screenshot.png",
  bottle1: "/assets/bottle1.png",
  bottle2: "/assets/bottle2.png",
  bottle3: "/assets/bottle3.png",
  vineyardCard: "/assets/vineyard-card.png",
  dashCard1: "/assets/dash-card1.png",
  dashCard2: "/assets/dash-card2.png",
  siteShot1: "/assets/site-shot1.png",
  siteShot2: "/assets/site-shot2.png",
  siteShot3: "/assets/site-shot3.png",
  siteShot4: "/assets/site-shot4.png",
  // Services page
  hubLaptop: "/assets/hub-screenshot.png",
  salesSheetCard: "/assets/sales-sheet-screenshot.png",
  vineyardWide: "/assets/vineyard-card.png",
  excelLogo: "/assets/excel-logo.png",
  // Wine bottle nodes for the services hero graphic
  bottleA: "/assets/bottle3.png",
  bottleB: "/assets/bottle2.png",
  bottleC: "/assets/bottle1.png",
  bottleD: "/assets/bottle3.png",
  bottleE: "/assets/bottle2.png",
  bottleF: "/assets/bottle1.png",
  bottleG: "/assets/bottle3.png",
};
